"""Record the pre-consolidation files and Git state without modifying sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
from pathlib import Path

ROOT_NAMES = (
    "burrau",
    "pythagorean-burrau",
    "pythagorean-burrau-fable",
    "pythagorean-burrau-fable-middle",
)
GENERATED_DIRS = {
    ".venv",
    ".pytest_cache",
    ".ruff_cache",
    ".mplconfig",
    ".tectonic-cache",
    "__pycache__",
    "oklo_fan_trajectory_cache",
}


def digest(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def git(root: Path, *args: str) -> str | None:
    result = subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=False
    )
    return result.stdout.strip() if result.returncode == 0 else None


def inventory(root: Path) -> dict:
    files, generated = [], []
    for directory, names, filenames in os.walk(root, followlinks=False):
        parent = Path(directory)
        for name in list(names):
            if name == ".git":
                names.remove(name)
            elif name in GENERATED_DIRS:
                child = parent / name
                generated.append(
                    {
                        "path": str(child.relative_to(root)),
                        "bytes": sum(
                            p.stat().st_size
                            for p in child.rglob("*")
                            if p.is_file() and not p.is_symlink()
                        ),
                    }
                )
                names.remove(name)
        for name in filenames:
            path = parent / name
            relative = str(path.relative_to(root))
            if name == ".git" or relative.startswith("archive/reorganization-2026-09-06/"):
                continue
            if name == ".DS_Store" or path.suffix in {".pyc", ".aux"}:
                generated.append({"path": relative, "bytes": path.stat().st_size})
            elif path.is_symlink():
                files.append({"path": relative, "symlink": os.readlink(path)})
            else:
                files.append(
                    {"path": relative, "bytes": path.stat().st_size, "sha256": digest(path)}
                )
    return {
        "head": git(root, "rev-parse", "HEAD"),
        "branch": git(root, "branch", "--show-current"),
        "status": git(root, "status", "--short"),
        "files": sorted(files, key=lambda row: row["path"]),
        "generated": sorted(generated, key=lambda row: row["path"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--projects", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = {"date": "2026-09-06", "roots": {}}
    for name in ROOT_NAMES:
        root = args.projects / name
        if not root.is_dir():
            raise SystemExit(f"Missing pre-consolidation root: {root}")
        record = inventory(root)
        result["roots"][name] = record
        print(
            f"{name}: {len(record['files'])} source/artifact files; "
            f"{sum(item['bytes'] for item in record['generated']):,} generated bytes"
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")


if __name__ == "__main__":
    main()
