"""Exact arithmetic of an explicit skinny Pythagorean family."""

from __future__ import annotations

import sympy as sp


def family_triple(index: sp.Expr) -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    """Return the Euclid family generated by (r,s)=(2*index,1)."""
    return 4 * index**2 - 1, 4 * index, 4 * index**2 + 1


def family_parameter(index: sp.Expr) -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    """Return u, A, and B for the explicit family."""
    u = 1 / (2 * index)
    denominator = 4 * index**2 + 1
    return u, (4 * index**2 - 1) / denominator, 4 * index / denominator


def family_reference_cycle_count(index: sp.Expr) -> sp.Expr:
    """Return Phi_ref(B_n)/(2*pi) in a positive real branch for index > 1/2."""
    return (
        (2 * index - 1) ** sp.Rational(3, 2)
        * (2 * index + 1)
        * (4 * index**2 + 1) ** sp.Rational(3, 4)
        / (32 * index ** sp.Rational(5, 2))
    )


def family_cycle_count_asymptotic() -> sp.Expr:
    """Return the expansion through index**(-3/2), without the O term."""
    index, inverse = sp.symbols("index inverse", positive=True)
    expression = family_reference_cycle_count(index).subs(index, 1 / inverse)
    expansion = sp.series(expression, inverse, 0, 2).removeO()
    return sp.expand(expansion.subs(inverse, 1 / index))


def family_cycle_count_second_derivative_asymptotic() -> sp.Expr:
    """Return the differentiated expansion needed for van der Corput."""
    index = sp.symbols("index", positive=True)
    return sp.expand(sp.diff(family_cycle_count_asymptotic(), index, 2))


def nonsquare_quartic_cycle_polynomial() -> tuple[sp.Expr, sp.Expr]:
    """Return the cubic polynomial and decaying remainder order for n=d*m**2."""
    d, m = sp.symbols("d m", positive=True)
    polynomial = d ** sp.Rational(3, 2) * m**3 / 2 - sp.sqrt(d) * m / 8
    remainder_scale = 1 / (sp.sqrt(d) * m)
    return polynomial, remainder_scale
