"""Rebuild manuscript vector figures from exact geometry and campaign JSON.

Run with Python, NumPy, and Matplotlib installed. The original fan PNG is
included unchanged and is not regenerated by this script.
"""

import json
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt

PAPER = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "pdf.fonttype": 42,
        "savefig.facecolor": "white",
    }
)
COLORS = ["#c64c40", "#42855b", "#345f9c"]


def geometry():
    fig, (ax, arc) = plt.subplots(1, 2, figsize=(9, 3.5), layout="constrained")
    pts = np.array([[-0.5, 0], [0.5, 0], [-0.14, 0.48]])
    ax.plot(*pts[[0, 1, 2, 0]].T, color="#8c8c8c", lw=1.5)
    for p, color in zip(pts, COLORS, strict=False):
        ax.scatter(*p, c=color, s=130, zorder=3, edgecolors="white")
    ax.text(-0.5, -0.075, r"$m_1=A=4/5$", ha="center", color=COLORS[0])
    ax.text(0.5, -0.075, r"$m_2=B=3/5$", ha="center", color=COLORS[1])
    ax.text(-0.14, 0.545, r"$m_3=1$", ha="center", color=COLORS[2])
    ax.text(-0.39, 0.25, r"$B=3/5$", ha="right")
    ax.text(0.24, 0.27, r"$A=4/5$", ha="left")
    ax.text(0, -0.025, r"$r_{12}=1$", ha="center", va="top")
    e1 = (pts[0] - pts[2]) / 0.6
    e2 = (pts[1] - pts[2]) / 0.8
    corner = np.array([pts[2] + 0.055 * e1, pts[2] + 0.055 * (e1 + e2), pts[2] + 0.055 * e2])
    ax.plot(*corner.T, color="#555555", lw=1)
    ax.set(xlim=(-0.77, 0.77), ylim=(-0.16, 0.69), aspect="equal")
    ax.axis("off")
    ax.set_title("A. Release all three bodies from rest", loc="left", fontsize=11)
    th = np.linspace(0, np.pi / 2, 300)
    arc.plot(np.cos(th), np.sin(th), color="#b8bdc3", lw=2)
    th = np.linspace(0, np.pi / 4, 200)
    arc.plot(np.cos(th), np.sin(th), color=COLORS[2], lw=3)
    arc.scatter([1], [0], facecolors="white", edgecolors=COLORS[2], zorder=5, s=45)
    arc.scatter([0.8, 2**-0.5], [0.6, 2**-0.5], color=COLORS[2], s=35)
    arc.annotate(
        r"$u=1/3$",
        (0.8, 0.6),
        xytext=(0.92, 0.68),
        arrowprops={"arrowstyle": "-", "color": "#777777"},
        fontsize=9,
    )
    arc.annotate(
        r"$u=\sqrt{2}-1$",
        (2**-0.5, 2**-0.5),
        xytext=(0.27, 0.88),
        arrowprops={"arrowstyle": "-", "color": "#777777"},
        fontsize=9,
    )
    arc.text(0.95, 0.075, r"$u\to0$", ha="right", fontsize=9)
    arc.text(0.08, 0.37, "Every rational $u$\ngives an integer triple.", fontsize=9)
    arc.set(
        xlim=(0, 1.16), ylim=(-0.035, 1.05), aspect="equal", xlabel=r"$A=m_1$", ylabel=r"$B=m_2$"
    )
    arc.set_title("B. One parameter ties masses to shape", loc="left", fontsize=11)
    fig.savefig(PAPER / "figures/initial-geometry.pdf")
    plt.close(fig)


def defects():
    data = json.loads((PAPER.parent / "data/periodic_atlas_campaign.json").read_text())
    rows = sorted(data["candidates"], key=lambda r: r["number"])
    ids = [r["number"] for r in rows]
    masses = np.array([r["parameters"][3:5] for r in rows])
    defect = (masses**2).sum(axis=1) - 1
    fig, (ax, bx) = plt.subplots(
        1, 2, figsize=(8.5, 3.8), gridspec_kw={"width_ratios": [1.05, 1]}, layout="constrained"
    )
    xx = np.linspace(0.29, 0.63, 300)
    ax.plot(xx, np.sqrt(1 - xx**2), color="#59616c", lw=1.4, label=r"Exact constraint $D=0$")
    offsets = {1: (-28, -11), 2: (8, -5), 3: (8, -3), 4: (8, 5), 5: (9, 5), 30: (-33, -14)}
    for n, (m1, m2), d in zip(ids, masses, defect, strict=False):
        color = COLORS[0] if d > 0 else COLORS[2]
        ax.scatter(m1, m2, s=45, c=color, zorder=3)
        ax.annotate(
            rf"$F_{{{n}}}$", (m1, m2), xytext=offsets[n], textcoords="offset points", fontsize=9
        )
    ax.set(xlim=(0.29, 0.64), ylim=(0.76, 0.975), xlabel=r"$m_1$", ylabel=r"$m_2$")
    ax.set_title("A. Candidates in the mass plane", loc="left", fontsize=11)
    ax.legend(loc="upper right", fontsize=8, frameon=False)
    bx.axvline(0, color="#59616c", lw=1)
    for i, d in enumerate(defect):
        col = COLORS[0] if d > 0 else COLORS[2]
        bx.plot([0, d], [i, i], color=col, lw=1.5)
        bx.scatter([d], [i], s=36, color=col)
    bx.set(
        yticks=range(len(ids)),
        yticklabels=[rf"$F_{{{n}}}$" for n in ids],
        xlabel=r"$D=m_1^2+m_2^2-1$",
        xlim=(-0.108, 0.04),
    )
    bx.invert_yaxis()
    bx.set_title("B. Signed right-triangle defects", loc="left", fontsize=11)
    bx.spines["left"].set_visible(False)
    bx.tick_params(axis="y", length=0)
    fig.savefig(PAPER / "figures/counterexample-defects.pdf")
    plt.close(fig)


if __name__ == "__main__":
    geometry()
    defects()
